// <auto-generated />
using API_NBA.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_NBA.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("API_NBA.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conferencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Imagen")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EquipoId");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("API_NBA.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AsistenciasporPartido")
                        .HasColumnType("REAL");

                    b.Property<double>("BloqueosporPartido")
                        .HasColumnType("REAL");

                    b.Property<int>("EquipoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PuntosporPartido")
                        .HasColumnType("REAL");

                    b.Property<double>("RebotesporPartido")
                        .HasColumnType("REAL");

                    b.Property<double>("RobosporPartido")
                        .HasColumnType("REAL");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugador");
                });
#pragma warning restore 612, 618
        }
    }
}
